# Generated by Django 5.0.3 on 2024-03-06 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLogradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro')),
                ('tipo_logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipologradouro')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('data_nasc', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
                ('tipo_pessoa', models.ManyToManyField(to='app.tipopessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('areaConstruida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeroComodos', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('numeroVagasGaragem', models.IntegerField()),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=100)),
                ('valorVendaAluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivelVenda', models.BooleanField()),
                ('disponivelLocacao', models.BooleanField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.logradouro')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
                ('tipo_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoimovel')),
                ('tipo_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipooferta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dataFinal', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imovel')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locador', to='app.pessoa')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locatario', to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='app.pessoa')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imovel')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='app.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf'),
        ),
    ]
